#!/bin/sh
title="GitDay"

cat <<EOF
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>$title</title>
	<style>
	body {
		width: min(35em, 85vw);
		margin: 0 auto;
		font-family: Tahoma, Verdana, Arial, sans-serif;
	}
	p em {
		display: block;
		text-align: right;
	}
	</style>
<head>

<body>
<h1>$title</h1>
EOF

template=$(cat <<EOF
<p id="%h">
<b>%s</b>
%b
<em>%ad</em>
</p>
EOF
)

git log --date=local --since="1 month ago" --format="$template"
git log --date=local --since="1 month ago" \
	--format="%C(red)%ad%C(reset) - %C(auto)%s%C(reset)" >&2

cat <<EOF
<hr />
<em>Generated by Gitday at $(date -u)</em>
</body>

</html>
EOF

